# Generated by Django 3.2.4 on 2021-07-08 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('ActivityID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('PricePH', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('ActivityCategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingItem', models.CharField(max_length=100)),
                ('itemName', models.CharField(max_length=100)),
                ('buildingItemLength', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('BuildingTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Area', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('Rooms', models.IntegerField(null=True)),
                ('Bathrooms', models.IntegerField(null=True)),
                ('Kitchens', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingTypeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingType', models.CharField(max_length=100)),
                ('buildingName', models.CharField(max_length=100)),
                ('buildingTypeLength', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentGroup',
            fields=[
                ('CurrentGroupID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('QuotationID', models.AutoField(primary_key=True, serialize=False)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Area', models.DecimalField(decimal_places=5, max_digits=20)),
                ('Rooms', models.IntegerField()),
                ('Bathrooms', models.IntegerField()),
                ('Kitchens', models.IntegerField()),
                ('BuildingTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oferty_App.buildingtype')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationStatus',
            fields=[
                ('QuotationStatusID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('TemplateID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateListItem',
            fields=[
                ('TemplateListID', models.AutoField(primary_key=True, serialize=False)),
                ('ActivityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oferty_App.activity')),
                ('TemplateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oferty_App.template')),
            ],
        ),
        migrations.CreateModel(
            name='rowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRowID', models.CharField(max_length=100)),
                ('data1td', models.CharField(max_length=100)),
                ('data2td', models.CharField(max_length=100, null=True)),
                ('data3td', models.CharField(max_length=100)),
                ('data4td', models.CharField(max_length=100, null=True)),
                ('data5td', models.CharField(max_length=100, null=True)),
                ('data6td', models.CharField(max_length=100, null=True)),
                ('data7td', models.CharField(max_length=100)),
                ('data8td', models.CharField(max_length=100, null=True)),
                ('data9td', models.CharField(max_length=100, null=True)),
                ('data10td', models.CharField(max_length=100)),
                ('buildingItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oferty_App.buildingitem')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('RoomTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('RoomName', models.CharField(max_length=100)),
                ('BuildingTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oferty_App.buildingtype')),
            ],
        ),
        migrations.CreateModel(
            name='RoomList',
            fields=[
                ('RoomListID', models.AutoField(primary_key=True, serialize=False)),
                ('QuotationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oferty_App.quotation')),
                ('RoomTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oferty_App.roomtype')),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='QuotationStatusID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oferty_App.quotationstatus'),
        ),
        migrations.AddField(
            model_name='buildingitem',
            name='buildingType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oferty_App.buildingtypedata'),
        ),
        migrations.CreateModel(
            name='ActivityListItem',
            fields=[
                ('ActivityListID', models.AutoField(primary_key=True, serialize=False)),
                ('ActivityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oferty_App.activity')),
                ('QuotationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oferty_App.quotation')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='ActivityCategoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oferty_App.activitycategory'),
        ),
    ]
